USE PEDIDOS

--- TOTAIS POR VENDEDOR
SELECT 
  V.CODVEN, V.NOME, V.FONE, SUM(P.VLR_TOTAL) AS TOT_VENDIDO,
  SUM(P.VLR_TOTAL * V.PORC_COMISSAO/100) AS COMISSAO,
  COUNT(*) AS QTD_PEDIDOS
FROM VENDEDORES V
  JOIN PEDIDOS P ON V.CODVEN = P.CODVEN
WHERE MONTH(P.DATA_EMISSAO) = 1 AND
      YEAR(P.DATA_EMISSAO) = 2007
GROUP BY V.CODVEN, V.NOME, V.FONE

--- PEDIDOS DO VENDEDOR
SELECT 
  P.NUM_PEDIDO, P.DATA_EMISSAO, P.VLR_TOTAL, C.NOME AS CLIENTE
FROM PEDIDOS P 
  JOIN CLIENTES C ON P.CODCLI = C.CODCLI 
WHERE
       MONTH(P.DATA_EMISSAO) = 1 AND
       YEAR(P.DATA_EMISSAO) = 2007 AND
       P.CODVEN = 1 -- código ligado ao vendedor
ORDER BY P.NUM_PEDIDO




