//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultaAlteraProdutos.ServiceProdutos {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProdutosConsulta", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ProdutosConsulta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ID_PRODUTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COD_PRODUTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESCRICAOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TIPOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UNIDADEField;
        
        private System.Nullable<decimal> PRECO_VENDAField;
        
        private System.Nullable<int> QTD_REALField;
        
        private System.Nullable<int> QTD_MINIMAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID_PRODUTO {
            get {
                return this.ID_PRODUTOField;
            }
            set {
                if ((this.ID_PRODUTOField.Equals(value) != true)) {
                    this.ID_PRODUTOField = value;
                    this.RaisePropertyChanged("ID_PRODUTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string COD_PRODUTO {
            get {
                return this.COD_PRODUTOField;
            }
            set {
                if ((object.ReferenceEquals(this.COD_PRODUTOField, value) != true)) {
                    this.COD_PRODUTOField = value;
                    this.RaisePropertyChanged("COD_PRODUTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DESCRICAO {
            get {
                return this.DESCRICAOField;
            }
            set {
                if ((object.ReferenceEquals(this.DESCRICAOField, value) != true)) {
                    this.DESCRICAOField = value;
                    this.RaisePropertyChanged("DESCRICAO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TIPO {
            get {
                return this.TIPOField;
            }
            set {
                if ((object.ReferenceEquals(this.TIPOField, value) != true)) {
                    this.TIPOField = value;
                    this.RaisePropertyChanged("TIPO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string UNIDADE {
            get {
                return this.UNIDADEField;
            }
            set {
                if ((object.ReferenceEquals(this.UNIDADEField, value) != true)) {
                    this.UNIDADEField = value;
                    this.RaisePropertyChanged("UNIDADE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<decimal> PRECO_VENDA {
            get {
                return this.PRECO_VENDAField;
            }
            set {
                if ((this.PRECO_VENDAField.Equals(value) != true)) {
                    this.PRECO_VENDAField = value;
                    this.RaisePropertyChanged("PRECO_VENDA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<int> QTD_REAL {
            get {
                return this.QTD_REALField;
            }
            set {
                if ((this.QTD_REALField.Equals(value) != true)) {
                    this.QTD_REALField = value;
                    this.RaisePropertyChanged("QTD_REAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<int> QTD_MINIMA {
            get {
                return this.QTD_MINIMAField;
            }
            set {
                if ((this.QTD_MINIMAField.Equals(value) != true)) {
                    this.QTD_MINIMAField = value;
                    this.RaisePropertyChanged("QTD_MINIMA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TIPOPRODUTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TIPOPRODUTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private short COD_TIPOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TIPOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsultaAlteraProdutos.ServiceProdutos.PRODUTOS PRODUTOSField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short COD_TIPO {
            get {
                return this.COD_TIPOField;
            }
            set {
                if ((this.COD_TIPOField.Equals(value) != true)) {
                    this.COD_TIPOField = value;
                    this.RaisePropertyChanged("COD_TIPO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TIPO {
            get {
                return this.TIPOField;
            }
            set {
                if ((object.ReferenceEquals(this.TIPOField, value) != true)) {
                    this.TIPOField = value;
                    this.RaisePropertyChanged("TIPO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ConsultaAlteraProdutos.ServiceProdutos.PRODUTOS PRODUTOS {
            get {
                return this.PRODUTOSField;
            }
            set {
                if ((object.ReferenceEquals(this.PRODUTOSField, value) != true)) {
                    this.PRODUTOSField = value;
                    this.RaisePropertyChanged("PRODUTOS");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PRODUTOS", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PRODUTOS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ID_PRODUTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COD_PRODUTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESCRICAOField;
        
        private System.Nullable<short> COD_UNIDADEField;
        
        private System.Nullable<short> COD_TIPOField;
        
        private System.Nullable<decimal> PRECO_CUSTOField;
        
        private System.Nullable<decimal> PRECO_VENDAField;
        
        private System.Nullable<int> QTD_ESTIMADAField;
        
        private System.Nullable<int> QTD_REALField;
        
        private System.Nullable<int> QTD_MINIMAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLAS_FISCField;
        
        private System.Nullable<int> IPIField;
        
        private System.Nullable<decimal> PESO_LIQField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsultaAlteraProdutos.ServiceProdutos.TIPOPRODUTO TIPOPRODUTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsultaAlteraProdutos.ServiceProdutos.UNIDADES UNIDADESField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID_PRODUTO {
            get {
                return this.ID_PRODUTOField;
            }
            set {
                if ((this.ID_PRODUTOField.Equals(value) != true)) {
                    this.ID_PRODUTOField = value;
                    this.RaisePropertyChanged("ID_PRODUTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string COD_PRODUTO {
            get {
                return this.COD_PRODUTOField;
            }
            set {
                if ((object.ReferenceEquals(this.COD_PRODUTOField, value) != true)) {
                    this.COD_PRODUTOField = value;
                    this.RaisePropertyChanged("COD_PRODUTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DESCRICAO {
            get {
                return this.DESCRICAOField;
            }
            set {
                if ((object.ReferenceEquals(this.DESCRICAOField, value) != true)) {
                    this.DESCRICAOField = value;
                    this.RaisePropertyChanged("DESCRICAO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<short> COD_UNIDADE {
            get {
                return this.COD_UNIDADEField;
            }
            set {
                if ((this.COD_UNIDADEField.Equals(value) != true)) {
                    this.COD_UNIDADEField = value;
                    this.RaisePropertyChanged("COD_UNIDADE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<short> COD_TIPO {
            get {
                return this.COD_TIPOField;
            }
            set {
                if ((this.COD_TIPOField.Equals(value) != true)) {
                    this.COD_TIPOField = value;
                    this.RaisePropertyChanged("COD_TIPO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<decimal> PRECO_CUSTO {
            get {
                return this.PRECO_CUSTOField;
            }
            set {
                if ((this.PRECO_CUSTOField.Equals(value) != true)) {
                    this.PRECO_CUSTOField = value;
                    this.RaisePropertyChanged("PRECO_CUSTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<decimal> PRECO_VENDA {
            get {
                return this.PRECO_VENDAField;
            }
            set {
                if ((this.PRECO_VENDAField.Equals(value) != true)) {
                    this.PRECO_VENDAField = value;
                    this.RaisePropertyChanged("PRECO_VENDA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<int> QTD_ESTIMADA {
            get {
                return this.QTD_ESTIMADAField;
            }
            set {
                if ((this.QTD_ESTIMADAField.Equals(value) != true)) {
                    this.QTD_ESTIMADAField = value;
                    this.RaisePropertyChanged("QTD_ESTIMADA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<int> QTD_REAL {
            get {
                return this.QTD_REALField;
            }
            set {
                if ((this.QTD_REALField.Equals(value) != true)) {
                    this.QTD_REALField = value;
                    this.RaisePropertyChanged("QTD_REAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.Nullable<int> QTD_MINIMA {
            get {
                return this.QTD_MINIMAField;
            }
            set {
                if ((this.QTD_MINIMAField.Equals(value) != true)) {
                    this.QTD_MINIMAField = value;
                    this.RaisePropertyChanged("QTD_MINIMA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string CLAS_FISC {
            get {
                return this.CLAS_FISCField;
            }
            set {
                if ((object.ReferenceEquals(this.CLAS_FISCField, value) != true)) {
                    this.CLAS_FISCField = value;
                    this.RaisePropertyChanged("CLAS_FISC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.Nullable<int> IPI {
            get {
                return this.IPIField;
            }
            set {
                if ((this.IPIField.Equals(value) != true)) {
                    this.IPIField = value;
                    this.RaisePropertyChanged("IPI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public System.Nullable<decimal> PESO_LIQ {
            get {
                return this.PESO_LIQField;
            }
            set {
                if ((this.PESO_LIQField.Equals(value) != true)) {
                    this.PESO_LIQField = value;
                    this.RaisePropertyChanged("PESO_LIQ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public ConsultaAlteraProdutos.ServiceProdutos.TIPOPRODUTO TIPOPRODUTO {
            get {
                return this.TIPOPRODUTOField;
            }
            set {
                if ((object.ReferenceEquals(this.TIPOPRODUTOField, value) != true)) {
                    this.TIPOPRODUTOField = value;
                    this.RaisePropertyChanged("TIPOPRODUTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public ConsultaAlteraProdutos.ServiceProdutos.UNIDADES UNIDADES {
            get {
                return this.UNIDADESField;
            }
            set {
                if ((object.ReferenceEquals(this.UNIDADESField, value) != true)) {
                    this.UNIDADESField = value;
                    this.RaisePropertyChanged("UNIDADES");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UNIDADES", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UNIDADES : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private short COD_UNIDADEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UNIDADEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsultaAlteraProdutos.ServiceProdutos.PRODUTOS PRODUTOSField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short COD_UNIDADE {
            get {
                return this.COD_UNIDADEField;
            }
            set {
                if ((this.COD_UNIDADEField.Equals(value) != true)) {
                    this.COD_UNIDADEField = value;
                    this.RaisePropertyChanged("COD_UNIDADE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UNIDADE {
            get {
                return this.UNIDADEField;
            }
            set {
                if ((object.ReferenceEquals(this.UNIDADEField, value) != true)) {
                    this.UNIDADEField = value;
                    this.RaisePropertyChanged("UNIDADE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ConsultaAlteraProdutos.ServiceProdutos.PRODUTOS PRODUTOS {
            get {
                return this.PRODUTOSField;
            }
            set {
                if ((object.ReferenceEquals(this.PRODUTOSField, value) != true)) {
                    this.PRODUTOSField = value;
                    this.RaisePropertyChanged("PRODUTOS");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="USUARIOS", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class USUARIOS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ID_USERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USER_LOGINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USER_PWSField;
        
        private System.Nullable<short> NIVELField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID_USER {
            get {
                return this.ID_USERField;
            }
            set {
                if ((this.ID_USERField.Equals(value) != true)) {
                    this.ID_USERField = value;
                    this.RaisePropertyChanged("ID_USER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NOME {
            get {
                return this.NOMEField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMEField, value) != true)) {
                    this.NOMEField = value;
                    this.RaisePropertyChanged("NOME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string USER_LOGIN {
            get {
                return this.USER_LOGINField;
            }
            set {
                if ((object.ReferenceEquals(this.USER_LOGINField, value) != true)) {
                    this.USER_LOGINField = value;
                    this.RaisePropertyChanged("USER_LOGIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string USER_PWS {
            get {
                return this.USER_PWSField;
            }
            set {
                if ((object.ReferenceEquals(this.USER_PWSField, value) != true)) {
                    this.USER_PWSField = value;
                    this.RaisePropertyChanged("USER_PWS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<short> NIVEL {
            get {
                return this.NIVELField;
            }
            set {
                if ((this.NIVELField.Equals(value) != true)) {
                    this.NIVELField = value;
                    this.RaisePropertyChanged("NIVEL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceProdutos.ServiceProdutosSoap")]
    public interface ServiceProdutosSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaProdutos", ReplyAction="*")]
        ConsultaAlteraProdutos.ServiceProdutos.ListaProdutosResponse ListaProdutos(ConsultaAlteraProdutos.ServiceProdutos.ListaProdutosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaProdutos", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsultaAlteraProdutos.ServiceProdutos.ListaProdutosResponse> ListaProdutosAsync(ConsultaAlteraProdutos.ServiceProdutos.ListaProdutosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReajustaPrecosIDs", ReplyAction="*")]
        ConsultaAlteraProdutos.ServiceProdutos.ReajustaPrecosIDsResponse ReajustaPrecosIDs(ConsultaAlteraProdutos.ServiceProdutos.ReajustaPrecosIDsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReajustaPrecosIDs", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsultaAlteraProdutos.ServiceProdutos.ReajustaPrecosIDsResponse> ReajustaPrecosIDsAsync(ConsultaAlteraProdutos.ServiceProdutos.ReajustaPrecosIDsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaTipos", ReplyAction="*")]
        ConsultaAlteraProdutos.ServiceProdutos.ListaTiposResponse ListaTipos(ConsultaAlteraProdutos.ServiceProdutos.ListaTiposRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaTipos", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsultaAlteraProdutos.ServiceProdutos.ListaTiposResponse> ListaTiposAsync(ConsultaAlteraProdutos.ServiceProdutos.ListaTiposRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaUnidades", ReplyAction="*")]
        ConsultaAlteraProdutos.ServiceProdutos.ListaUnidadesResponse ListaUnidades(ConsultaAlteraProdutos.ServiceProdutos.ListaUnidadesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaUnidades", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsultaAlteraProdutos.ServiceProdutos.ListaUnidadesResponse> ListaUnidadesAsync(ConsultaAlteraProdutos.ServiceProdutos.ListaUnidadesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FichaProduto", ReplyAction="*")]
        ConsultaAlteraProdutos.ServiceProdutos.FichaProdutoResponse FichaProduto(ConsultaAlteraProdutos.ServiceProdutos.FichaProdutoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FichaProduto", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsultaAlteraProdutos.ServiceProdutos.FichaProdutoResponse> FichaProdutoAsync(ConsultaAlteraProdutos.ServiceProdutos.FichaProdutoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AlterProduto", ReplyAction="*")]
        ConsultaAlteraProdutos.ServiceProdutos.AlterProdutoResponse AlterProduto(ConsultaAlteraProdutos.ServiceProdutos.AlterProdutoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AlterProduto", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsultaAlteraProdutos.ServiceProdutos.AlterProdutoResponse> AlterProdutoAsync(ConsultaAlteraProdutos.ServiceProdutos.AlterProdutoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsereProduto", ReplyAction="*")]
        ConsultaAlteraProdutos.ServiceProdutos.InsereProdutoResponse InsereProduto(ConsultaAlteraProdutos.ServiceProdutos.InsereProdutoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsereProduto", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsultaAlteraProdutos.ServiceProdutos.InsereProdutoResponse> InsereProdutoAsync(ConsultaAlteraProdutos.ServiceProdutos.InsereProdutoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExcluiProduto", ReplyAction="*")]
        ConsultaAlteraProdutos.ServiceProdutos.ExcluiProdutoResponse ExcluiProduto(ConsultaAlteraProdutos.ServiceProdutos.ExcluiProdutoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExcluiProduto", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsultaAlteraProdutos.ServiceProdutos.ExcluiProdutoResponse> ExcluiProdutoAsync(ConsultaAlteraProdutos.ServiceProdutos.ExcluiProdutoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DadosUsuario", ReplyAction="*")]
        ConsultaAlteraProdutos.ServiceProdutos.DadosUsuarioResponse DadosUsuario(ConsultaAlteraProdutos.ServiceProdutos.DadosUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DadosUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsultaAlteraProdutos.ServiceProdutos.DadosUsuarioResponse> DadosUsuarioAsync(ConsultaAlteraProdutos.ServiceProdutos.DadosUsuarioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaProdutosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaProdutos", Namespace="http://tempuri.org/", Order=0)]
        public ConsultaAlteraProdutos.ServiceProdutos.ListaProdutosRequestBody Body;
        
        public ListaProdutosRequest() {
        }
        
        public ListaProdutosRequest(ConsultaAlteraProdutos.ServiceProdutos.ListaProdutosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaProdutosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string descr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tipo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string erro;
        
        public ListaProdutosRequestBody() {
        }
        
        public ListaProdutosRequestBody(string descr, string tipo, string erro) {
            this.descr = descr;
            this.tipo = tipo;
            this.erro = erro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaProdutosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaProdutosResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsultaAlteraProdutos.ServiceProdutos.ListaProdutosResponseBody Body;
        
        public ListaProdutosResponse() {
        }
        
        public ListaProdutosResponse(ConsultaAlteraProdutos.ServiceProdutos.ListaProdutosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaProdutosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsultaAlteraProdutos.ServiceProdutos.ProdutosConsulta[] ListaProdutosResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string erro;
        
        public ListaProdutosResponseBody() {
        }
        
        public ListaProdutosResponseBody(ConsultaAlteraProdutos.ServiceProdutos.ProdutosConsulta[] ListaProdutosResult, string erro) {
            this.ListaProdutosResult = ListaProdutosResult;
            this.erro = erro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReajustaPrecosIDsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReajustaPrecosIDs", Namespace="http://tempuri.org/", Order=0)]
        public ConsultaAlteraProdutos.ServiceProdutos.ReajustaPrecosIDsRequestBody Body;
        
        public ReajustaPrecosIDsRequest() {
        }
        
        public ReajustaPrecosIDsRequest(ConsultaAlteraProdutos.ServiceProdutos.ReajustaPrecosIDsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReajustaPrecosIDsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ids;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public decimal porc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string erro;
        
        public ReajustaPrecosIDsRequestBody() {
        }
        
        public ReajustaPrecosIDsRequestBody(string ids, decimal porc, string erro) {
            this.ids = ids;
            this.porc = porc;
            this.erro = erro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReajustaPrecosIDsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReajustaPrecosIDsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsultaAlteraProdutos.ServiceProdutos.ReajustaPrecosIDsResponseBody Body;
        
        public ReajustaPrecosIDsResponse() {
        }
        
        public ReajustaPrecosIDsResponse(ConsultaAlteraProdutos.ServiceProdutos.ReajustaPrecosIDsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReajustaPrecosIDsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ReajustaPrecosIDsResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string erro;
        
        public ReajustaPrecosIDsResponseBody() {
        }
        
        public ReajustaPrecosIDsResponseBody(int ReajustaPrecosIDsResult, string erro) {
            this.ReajustaPrecosIDsResult = ReajustaPrecosIDsResult;
            this.erro = erro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaTiposRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaTipos", Namespace="http://tempuri.org/", Order=0)]
        public ConsultaAlteraProdutos.ServiceProdutos.ListaTiposRequestBody Body;
        
        public ListaTiposRequest() {
        }
        
        public ListaTiposRequest(ConsultaAlteraProdutos.ServiceProdutos.ListaTiposRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaTiposRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string erro;
        
        public ListaTiposRequestBody() {
        }
        
        public ListaTiposRequestBody(string erro) {
            this.erro = erro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaTiposResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaTiposResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsultaAlteraProdutos.ServiceProdutos.ListaTiposResponseBody Body;
        
        public ListaTiposResponse() {
        }
        
        public ListaTiposResponse(ConsultaAlteraProdutos.ServiceProdutos.ListaTiposResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaTiposResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsultaAlteraProdutos.ServiceProdutos.TIPOPRODUTO[] ListaTiposResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string erro;
        
        public ListaTiposResponseBody() {
        }
        
        public ListaTiposResponseBody(ConsultaAlteraProdutos.ServiceProdutos.TIPOPRODUTO[] ListaTiposResult, string erro) {
            this.ListaTiposResult = ListaTiposResult;
            this.erro = erro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaUnidadesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaUnidades", Namespace="http://tempuri.org/", Order=0)]
        public ConsultaAlteraProdutos.ServiceProdutos.ListaUnidadesRequestBody Body;
        
        public ListaUnidadesRequest() {
        }
        
        public ListaUnidadesRequest(ConsultaAlteraProdutos.ServiceProdutos.ListaUnidadesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaUnidadesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string erro;
        
        public ListaUnidadesRequestBody() {
        }
        
        public ListaUnidadesRequestBody(string erro) {
            this.erro = erro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaUnidadesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaUnidadesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsultaAlteraProdutos.ServiceProdutos.ListaUnidadesResponseBody Body;
        
        public ListaUnidadesResponse() {
        }
        
        public ListaUnidadesResponse(ConsultaAlteraProdutos.ServiceProdutos.ListaUnidadesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaUnidadesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsultaAlteraProdutos.ServiceProdutos.UNIDADES[] ListaUnidadesResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string erro;
        
        public ListaUnidadesResponseBody() {
        }
        
        public ListaUnidadesResponseBody(ConsultaAlteraProdutos.ServiceProdutos.UNIDADES[] ListaUnidadesResult, string erro) {
            this.ListaUnidadesResult = ListaUnidadesResult;
            this.erro = erro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FichaProdutoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FichaProduto", Namespace="http://tempuri.org/", Order=0)]
        public ConsultaAlteraProdutos.ServiceProdutos.FichaProdutoRequestBody Body;
        
        public FichaProdutoRequest() {
        }
        
        public FichaProdutoRequest(ConsultaAlteraProdutos.ServiceProdutos.FichaProdutoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FichaProdutoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idProduto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string erro;
        
        public FichaProdutoRequestBody() {
        }
        
        public FichaProdutoRequestBody(int idProduto, string erro) {
            this.idProduto = idProduto;
            this.erro = erro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FichaProdutoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FichaProdutoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsultaAlteraProdutos.ServiceProdutos.FichaProdutoResponseBody Body;
        
        public FichaProdutoResponse() {
        }
        
        public FichaProdutoResponse(ConsultaAlteraProdutos.ServiceProdutos.FichaProdutoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FichaProdutoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsultaAlteraProdutos.ServiceProdutos.PRODUTOS FichaProdutoResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string erro;
        
        public FichaProdutoResponseBody() {
        }
        
        public FichaProdutoResponseBody(ConsultaAlteraProdutos.ServiceProdutos.PRODUTOS FichaProdutoResult, string erro) {
            this.FichaProdutoResult = FichaProdutoResult;
            this.erro = erro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AlterProdutoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AlterProduto", Namespace="http://tempuri.org/", Order=0)]
        public ConsultaAlteraProdutos.ServiceProdutos.AlterProdutoRequestBody Body;
        
        public AlterProdutoRequest() {
        }
        
        public AlterProdutoRequest(ConsultaAlteraProdutos.ServiceProdutos.AlterProdutoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AlterProdutoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsultaAlteraProdutos.ServiceProdutos.PRODUTOS pr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string erro;
        
        public AlterProdutoRequestBody() {
        }
        
        public AlterProdutoRequestBody(ConsultaAlteraProdutos.ServiceProdutos.PRODUTOS pr, string erro) {
            this.pr = pr;
            this.erro = erro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AlterProdutoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AlterProdutoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsultaAlteraProdutos.ServiceProdutos.AlterProdutoResponseBody Body;
        
        public AlterProdutoResponse() {
        }
        
        public AlterProdutoResponse(ConsultaAlteraProdutos.ServiceProdutos.AlterProdutoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AlterProdutoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string erro;
        
        public AlterProdutoResponseBody() {
        }
        
        public AlterProdutoResponseBody(string erro) {
            this.erro = erro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsereProdutoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsereProduto", Namespace="http://tempuri.org/", Order=0)]
        public ConsultaAlteraProdutos.ServiceProdutos.InsereProdutoRequestBody Body;
        
        public InsereProdutoRequest() {
        }
        
        public InsereProdutoRequest(ConsultaAlteraProdutos.ServiceProdutos.InsereProdutoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsereProdutoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsultaAlteraProdutos.ServiceProdutos.PRODUTOS pr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string erro;
        
        public InsereProdutoRequestBody() {
        }
        
        public InsereProdutoRequestBody(ConsultaAlteraProdutos.ServiceProdutos.PRODUTOS pr, string erro) {
            this.pr = pr;
            this.erro = erro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsereProdutoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsereProdutoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsultaAlteraProdutos.ServiceProdutos.InsereProdutoResponseBody Body;
        
        public InsereProdutoResponse() {
        }
        
        public InsereProdutoResponse(ConsultaAlteraProdutos.ServiceProdutos.InsereProdutoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsereProdutoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int InsereProdutoResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string erro;
        
        public InsereProdutoResponseBody() {
        }
        
        public InsereProdutoResponseBody(int InsereProdutoResult, string erro) {
            this.InsereProdutoResult = InsereProdutoResult;
            this.erro = erro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExcluiProdutoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExcluiProduto", Namespace="http://tempuri.org/", Order=0)]
        public ConsultaAlteraProdutos.ServiceProdutos.ExcluiProdutoRequestBody Body;
        
        public ExcluiProdutoRequest() {
        }
        
        public ExcluiProdutoRequest(ConsultaAlteraProdutos.ServiceProdutos.ExcluiProdutoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExcluiProdutoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idProduto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string erro;
        
        public ExcluiProdutoRequestBody() {
        }
        
        public ExcluiProdutoRequestBody(int idProduto, string erro) {
            this.idProduto = idProduto;
            this.erro = erro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExcluiProdutoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExcluiProdutoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsultaAlteraProdutos.ServiceProdutos.ExcluiProdutoResponseBody Body;
        
        public ExcluiProdutoResponse() {
        }
        
        public ExcluiProdutoResponse(ConsultaAlteraProdutos.ServiceProdutos.ExcluiProdutoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExcluiProdutoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string erro;
        
        public ExcluiProdutoResponseBody() {
        }
        
        public ExcluiProdutoResponseBody(string erro) {
            this.erro = erro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DadosUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DadosUsuario", Namespace="http://tempuri.org/", Order=0)]
        public ConsultaAlteraProdutos.ServiceProdutos.DadosUsuarioRequestBody Body;
        
        public DadosUsuarioRequest() {
        }
        
        public DadosUsuarioRequest(ConsultaAlteraProdutos.ServiceProdutos.DadosUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DadosUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string senha;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string erro;
        
        public DadosUsuarioRequestBody() {
        }
        
        public DadosUsuarioRequestBody(string login, string senha, string erro) {
            this.login = login;
            this.senha = senha;
            this.erro = erro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DadosUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DadosUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsultaAlteraProdutos.ServiceProdutos.DadosUsuarioResponseBody Body;
        
        public DadosUsuarioResponse() {
        }
        
        public DadosUsuarioResponse(ConsultaAlteraProdutos.ServiceProdutos.DadosUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DadosUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsultaAlteraProdutos.ServiceProdutos.USUARIOS DadosUsuarioResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string erro;
        
        public DadosUsuarioResponseBody() {
        }
        
        public DadosUsuarioResponseBody(ConsultaAlteraProdutos.ServiceProdutos.USUARIOS DadosUsuarioResult, string erro) {
            this.DadosUsuarioResult = DadosUsuarioResult;
            this.erro = erro;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceProdutosSoapChannel : ConsultaAlteraProdutos.ServiceProdutos.ServiceProdutosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceProdutosSoapClient : System.ServiceModel.ClientBase<ConsultaAlteraProdutos.ServiceProdutos.ServiceProdutosSoap>, ConsultaAlteraProdutos.ServiceProdutos.ServiceProdutosSoap {
        
        public ServiceProdutosSoapClient() {
        }
        
        public ServiceProdutosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceProdutosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceProdutosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceProdutosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsultaAlteraProdutos.ServiceProdutos.ListaProdutosResponse ConsultaAlteraProdutos.ServiceProdutos.ServiceProdutosSoap.ListaProdutos(ConsultaAlteraProdutos.ServiceProdutos.ListaProdutosRequest request) {
            return base.Channel.ListaProdutos(request);
        }
        
        public ConsultaAlteraProdutos.ServiceProdutos.ProdutosConsulta[] ListaProdutos(string descr, string tipo, ref string erro) {
            ConsultaAlteraProdutos.ServiceProdutos.ListaProdutosRequest inValue = new ConsultaAlteraProdutos.ServiceProdutos.ListaProdutosRequest();
            inValue.Body = new ConsultaAlteraProdutos.ServiceProdutos.ListaProdutosRequestBody();
            inValue.Body.descr = descr;
            inValue.Body.tipo = tipo;
            inValue.Body.erro = erro;
            ConsultaAlteraProdutos.ServiceProdutos.ListaProdutosResponse retVal = ((ConsultaAlteraProdutos.ServiceProdutos.ServiceProdutosSoap)(this)).ListaProdutos(inValue);
            erro = retVal.Body.erro;
            return retVal.Body.ListaProdutosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsultaAlteraProdutos.ServiceProdutos.ListaProdutosResponse> ConsultaAlteraProdutos.ServiceProdutos.ServiceProdutosSoap.ListaProdutosAsync(ConsultaAlteraProdutos.ServiceProdutos.ListaProdutosRequest request) {
            return base.Channel.ListaProdutosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsultaAlteraProdutos.ServiceProdutos.ListaProdutosResponse> ListaProdutosAsync(string descr, string tipo, string erro) {
            ConsultaAlteraProdutos.ServiceProdutos.ListaProdutosRequest inValue = new ConsultaAlteraProdutos.ServiceProdutos.ListaProdutosRequest();
            inValue.Body = new ConsultaAlteraProdutos.ServiceProdutos.ListaProdutosRequestBody();
            inValue.Body.descr = descr;
            inValue.Body.tipo = tipo;
            inValue.Body.erro = erro;
            return ((ConsultaAlteraProdutos.ServiceProdutos.ServiceProdutosSoap)(this)).ListaProdutosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsultaAlteraProdutos.ServiceProdutos.ReajustaPrecosIDsResponse ConsultaAlteraProdutos.ServiceProdutos.ServiceProdutosSoap.ReajustaPrecosIDs(ConsultaAlteraProdutos.ServiceProdutos.ReajustaPrecosIDsRequest request) {
            return base.Channel.ReajustaPrecosIDs(request);
        }
        
        public int ReajustaPrecosIDs(string ids, decimal porc, ref string erro) {
            ConsultaAlteraProdutos.ServiceProdutos.ReajustaPrecosIDsRequest inValue = new ConsultaAlteraProdutos.ServiceProdutos.ReajustaPrecosIDsRequest();
            inValue.Body = new ConsultaAlteraProdutos.ServiceProdutos.ReajustaPrecosIDsRequestBody();
            inValue.Body.ids = ids;
            inValue.Body.porc = porc;
            inValue.Body.erro = erro;
            ConsultaAlteraProdutos.ServiceProdutos.ReajustaPrecosIDsResponse retVal = ((ConsultaAlteraProdutos.ServiceProdutos.ServiceProdutosSoap)(this)).ReajustaPrecosIDs(inValue);
            erro = retVal.Body.erro;
            return retVal.Body.ReajustaPrecosIDsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsultaAlteraProdutos.ServiceProdutos.ReajustaPrecosIDsResponse> ConsultaAlteraProdutos.ServiceProdutos.ServiceProdutosSoap.ReajustaPrecosIDsAsync(ConsultaAlteraProdutos.ServiceProdutos.ReajustaPrecosIDsRequest request) {
            return base.Channel.ReajustaPrecosIDsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsultaAlteraProdutos.ServiceProdutos.ReajustaPrecosIDsResponse> ReajustaPrecosIDsAsync(string ids, decimal porc, string erro) {
            ConsultaAlteraProdutos.ServiceProdutos.ReajustaPrecosIDsRequest inValue = new ConsultaAlteraProdutos.ServiceProdutos.ReajustaPrecosIDsRequest();
            inValue.Body = new ConsultaAlteraProdutos.ServiceProdutos.ReajustaPrecosIDsRequestBody();
            inValue.Body.ids = ids;
            inValue.Body.porc = porc;
            inValue.Body.erro = erro;
            return ((ConsultaAlteraProdutos.ServiceProdutos.ServiceProdutosSoap)(this)).ReajustaPrecosIDsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsultaAlteraProdutos.ServiceProdutos.ListaTiposResponse ConsultaAlteraProdutos.ServiceProdutos.ServiceProdutosSoap.ListaTipos(ConsultaAlteraProdutos.ServiceProdutos.ListaTiposRequest request) {
            return base.Channel.ListaTipos(request);
        }
        
        public ConsultaAlteraProdutos.ServiceProdutos.TIPOPRODUTO[] ListaTipos(ref string erro) {
            ConsultaAlteraProdutos.ServiceProdutos.ListaTiposRequest inValue = new ConsultaAlteraProdutos.ServiceProdutos.ListaTiposRequest();
            inValue.Body = new ConsultaAlteraProdutos.ServiceProdutos.ListaTiposRequestBody();
            inValue.Body.erro = erro;
            ConsultaAlteraProdutos.ServiceProdutos.ListaTiposResponse retVal = ((ConsultaAlteraProdutos.ServiceProdutos.ServiceProdutosSoap)(this)).ListaTipos(inValue);
            erro = retVal.Body.erro;
            return retVal.Body.ListaTiposResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsultaAlteraProdutos.ServiceProdutos.ListaTiposResponse> ConsultaAlteraProdutos.ServiceProdutos.ServiceProdutosSoap.ListaTiposAsync(ConsultaAlteraProdutos.ServiceProdutos.ListaTiposRequest request) {
            return base.Channel.ListaTiposAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsultaAlteraProdutos.ServiceProdutos.ListaTiposResponse> ListaTiposAsync(string erro) {
            ConsultaAlteraProdutos.ServiceProdutos.ListaTiposRequest inValue = new ConsultaAlteraProdutos.ServiceProdutos.ListaTiposRequest();
            inValue.Body = new ConsultaAlteraProdutos.ServiceProdutos.ListaTiposRequestBody();
            inValue.Body.erro = erro;
            return ((ConsultaAlteraProdutos.ServiceProdutos.ServiceProdutosSoap)(this)).ListaTiposAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsultaAlteraProdutos.ServiceProdutos.ListaUnidadesResponse ConsultaAlteraProdutos.ServiceProdutos.ServiceProdutosSoap.ListaUnidades(ConsultaAlteraProdutos.ServiceProdutos.ListaUnidadesRequest request) {
            return base.Channel.ListaUnidades(request);
        }
        
        public ConsultaAlteraProdutos.ServiceProdutos.UNIDADES[] ListaUnidades(ref string erro) {
            ConsultaAlteraProdutos.ServiceProdutos.ListaUnidadesRequest inValue = new ConsultaAlteraProdutos.ServiceProdutos.ListaUnidadesRequest();
            inValue.Body = new ConsultaAlteraProdutos.ServiceProdutos.ListaUnidadesRequestBody();
            inValue.Body.erro = erro;
            ConsultaAlteraProdutos.ServiceProdutos.ListaUnidadesResponse retVal = ((ConsultaAlteraProdutos.ServiceProdutos.ServiceProdutosSoap)(this)).ListaUnidades(inValue);
            erro = retVal.Body.erro;
            return retVal.Body.ListaUnidadesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsultaAlteraProdutos.ServiceProdutos.ListaUnidadesResponse> ConsultaAlteraProdutos.ServiceProdutos.ServiceProdutosSoap.ListaUnidadesAsync(ConsultaAlteraProdutos.ServiceProdutos.ListaUnidadesRequest request) {
            return base.Channel.ListaUnidadesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsultaAlteraProdutos.ServiceProdutos.ListaUnidadesResponse> ListaUnidadesAsync(string erro) {
            ConsultaAlteraProdutos.ServiceProdutos.ListaUnidadesRequest inValue = new ConsultaAlteraProdutos.ServiceProdutos.ListaUnidadesRequest();
            inValue.Body = new ConsultaAlteraProdutos.ServiceProdutos.ListaUnidadesRequestBody();
            inValue.Body.erro = erro;
            return ((ConsultaAlteraProdutos.ServiceProdutos.ServiceProdutosSoap)(this)).ListaUnidadesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsultaAlteraProdutos.ServiceProdutos.FichaProdutoResponse ConsultaAlteraProdutos.ServiceProdutos.ServiceProdutosSoap.FichaProduto(ConsultaAlteraProdutos.ServiceProdutos.FichaProdutoRequest request) {
            return base.Channel.FichaProduto(request);
        }
        
        public ConsultaAlteraProdutos.ServiceProdutos.PRODUTOS FichaProduto(int idProduto, ref string erro) {
            ConsultaAlteraProdutos.ServiceProdutos.FichaProdutoRequest inValue = new ConsultaAlteraProdutos.ServiceProdutos.FichaProdutoRequest();
            inValue.Body = new ConsultaAlteraProdutos.ServiceProdutos.FichaProdutoRequestBody();
            inValue.Body.idProduto = idProduto;
            inValue.Body.erro = erro;
            ConsultaAlteraProdutos.ServiceProdutos.FichaProdutoResponse retVal = ((ConsultaAlteraProdutos.ServiceProdutos.ServiceProdutosSoap)(this)).FichaProduto(inValue);
            erro = retVal.Body.erro;
            return retVal.Body.FichaProdutoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsultaAlteraProdutos.ServiceProdutos.FichaProdutoResponse> ConsultaAlteraProdutos.ServiceProdutos.ServiceProdutosSoap.FichaProdutoAsync(ConsultaAlteraProdutos.ServiceProdutos.FichaProdutoRequest request) {
            return base.Channel.FichaProdutoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsultaAlteraProdutos.ServiceProdutos.FichaProdutoResponse> FichaProdutoAsync(int idProduto, string erro) {
            ConsultaAlteraProdutos.ServiceProdutos.FichaProdutoRequest inValue = new ConsultaAlteraProdutos.ServiceProdutos.FichaProdutoRequest();
            inValue.Body = new ConsultaAlteraProdutos.ServiceProdutos.FichaProdutoRequestBody();
            inValue.Body.idProduto = idProduto;
            inValue.Body.erro = erro;
            return ((ConsultaAlteraProdutos.ServiceProdutos.ServiceProdutosSoap)(this)).FichaProdutoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsultaAlteraProdutos.ServiceProdutos.AlterProdutoResponse ConsultaAlteraProdutos.ServiceProdutos.ServiceProdutosSoap.AlterProduto(ConsultaAlteraProdutos.ServiceProdutos.AlterProdutoRequest request) {
            return base.Channel.AlterProduto(request);
        }
        
        public void AlterProduto(ConsultaAlteraProdutos.ServiceProdutos.PRODUTOS pr, ref string erro) {
            ConsultaAlteraProdutos.ServiceProdutos.AlterProdutoRequest inValue = new ConsultaAlteraProdutos.ServiceProdutos.AlterProdutoRequest();
            inValue.Body = new ConsultaAlteraProdutos.ServiceProdutos.AlterProdutoRequestBody();
            inValue.Body.pr = pr;
            inValue.Body.erro = erro;
            ConsultaAlteraProdutos.ServiceProdutos.AlterProdutoResponse retVal = ((ConsultaAlteraProdutos.ServiceProdutos.ServiceProdutosSoap)(this)).AlterProduto(inValue);
            erro = retVal.Body.erro;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsultaAlteraProdutos.ServiceProdutos.AlterProdutoResponse> ConsultaAlteraProdutos.ServiceProdutos.ServiceProdutosSoap.AlterProdutoAsync(ConsultaAlteraProdutos.ServiceProdutos.AlterProdutoRequest request) {
            return base.Channel.AlterProdutoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsultaAlteraProdutos.ServiceProdutos.AlterProdutoResponse> AlterProdutoAsync(ConsultaAlteraProdutos.ServiceProdutos.PRODUTOS pr, string erro) {
            ConsultaAlteraProdutos.ServiceProdutos.AlterProdutoRequest inValue = new ConsultaAlteraProdutos.ServiceProdutos.AlterProdutoRequest();
            inValue.Body = new ConsultaAlteraProdutos.ServiceProdutos.AlterProdutoRequestBody();
            inValue.Body.pr = pr;
            inValue.Body.erro = erro;
            return ((ConsultaAlteraProdutos.ServiceProdutos.ServiceProdutosSoap)(this)).AlterProdutoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsultaAlteraProdutos.ServiceProdutos.InsereProdutoResponse ConsultaAlteraProdutos.ServiceProdutos.ServiceProdutosSoap.InsereProduto(ConsultaAlteraProdutos.ServiceProdutos.InsereProdutoRequest request) {
            return base.Channel.InsereProduto(request);
        }
        
        public int InsereProduto(ConsultaAlteraProdutos.ServiceProdutos.PRODUTOS pr, ref string erro) {
            ConsultaAlteraProdutos.ServiceProdutos.InsereProdutoRequest inValue = new ConsultaAlteraProdutos.ServiceProdutos.InsereProdutoRequest();
            inValue.Body = new ConsultaAlteraProdutos.ServiceProdutos.InsereProdutoRequestBody();
            inValue.Body.pr = pr;
            inValue.Body.erro = erro;
            ConsultaAlteraProdutos.ServiceProdutos.InsereProdutoResponse retVal = ((ConsultaAlteraProdutos.ServiceProdutos.ServiceProdutosSoap)(this)).InsereProduto(inValue);
            erro = retVal.Body.erro;
            return retVal.Body.InsereProdutoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsultaAlteraProdutos.ServiceProdutos.InsereProdutoResponse> ConsultaAlteraProdutos.ServiceProdutos.ServiceProdutosSoap.InsereProdutoAsync(ConsultaAlteraProdutos.ServiceProdutos.InsereProdutoRequest request) {
            return base.Channel.InsereProdutoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsultaAlteraProdutos.ServiceProdutos.InsereProdutoResponse> InsereProdutoAsync(ConsultaAlteraProdutos.ServiceProdutos.PRODUTOS pr, string erro) {
            ConsultaAlteraProdutos.ServiceProdutos.InsereProdutoRequest inValue = new ConsultaAlteraProdutos.ServiceProdutos.InsereProdutoRequest();
            inValue.Body = new ConsultaAlteraProdutos.ServiceProdutos.InsereProdutoRequestBody();
            inValue.Body.pr = pr;
            inValue.Body.erro = erro;
            return ((ConsultaAlteraProdutos.ServiceProdutos.ServiceProdutosSoap)(this)).InsereProdutoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsultaAlteraProdutos.ServiceProdutos.ExcluiProdutoResponse ConsultaAlteraProdutos.ServiceProdutos.ServiceProdutosSoap.ExcluiProduto(ConsultaAlteraProdutos.ServiceProdutos.ExcluiProdutoRequest request) {
            return base.Channel.ExcluiProduto(request);
        }
        
        public void ExcluiProduto(int idProduto, ref string erro) {
            ConsultaAlteraProdutos.ServiceProdutos.ExcluiProdutoRequest inValue = new ConsultaAlteraProdutos.ServiceProdutos.ExcluiProdutoRequest();
            inValue.Body = new ConsultaAlteraProdutos.ServiceProdutos.ExcluiProdutoRequestBody();
            inValue.Body.idProduto = idProduto;
            inValue.Body.erro = erro;
            ConsultaAlteraProdutos.ServiceProdutos.ExcluiProdutoResponse retVal = ((ConsultaAlteraProdutos.ServiceProdutos.ServiceProdutosSoap)(this)).ExcluiProduto(inValue);
            erro = retVal.Body.erro;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsultaAlteraProdutos.ServiceProdutos.ExcluiProdutoResponse> ConsultaAlteraProdutos.ServiceProdutos.ServiceProdutosSoap.ExcluiProdutoAsync(ConsultaAlteraProdutos.ServiceProdutos.ExcluiProdutoRequest request) {
            return base.Channel.ExcluiProdutoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsultaAlteraProdutos.ServiceProdutos.ExcluiProdutoResponse> ExcluiProdutoAsync(int idProduto, string erro) {
            ConsultaAlteraProdutos.ServiceProdutos.ExcluiProdutoRequest inValue = new ConsultaAlteraProdutos.ServiceProdutos.ExcluiProdutoRequest();
            inValue.Body = new ConsultaAlteraProdutos.ServiceProdutos.ExcluiProdutoRequestBody();
            inValue.Body.idProduto = idProduto;
            inValue.Body.erro = erro;
            return ((ConsultaAlteraProdutos.ServiceProdutos.ServiceProdutosSoap)(this)).ExcluiProdutoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsultaAlteraProdutos.ServiceProdutos.DadosUsuarioResponse ConsultaAlteraProdutos.ServiceProdutos.ServiceProdutosSoap.DadosUsuario(ConsultaAlteraProdutos.ServiceProdutos.DadosUsuarioRequest request) {
            return base.Channel.DadosUsuario(request);
        }
        
        public ConsultaAlteraProdutos.ServiceProdutos.USUARIOS DadosUsuario(string login, string senha, ref string erro) {
            ConsultaAlteraProdutos.ServiceProdutos.DadosUsuarioRequest inValue = new ConsultaAlteraProdutos.ServiceProdutos.DadosUsuarioRequest();
            inValue.Body = new ConsultaAlteraProdutos.ServiceProdutos.DadosUsuarioRequestBody();
            inValue.Body.login = login;
            inValue.Body.senha = senha;
            inValue.Body.erro = erro;
            ConsultaAlteraProdutos.ServiceProdutos.DadosUsuarioResponse retVal = ((ConsultaAlteraProdutos.ServiceProdutos.ServiceProdutosSoap)(this)).DadosUsuario(inValue);
            erro = retVal.Body.erro;
            return retVal.Body.DadosUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsultaAlteraProdutos.ServiceProdutos.DadosUsuarioResponse> ConsultaAlteraProdutos.ServiceProdutos.ServiceProdutosSoap.DadosUsuarioAsync(ConsultaAlteraProdutos.ServiceProdutos.DadosUsuarioRequest request) {
            return base.Channel.DadosUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsultaAlteraProdutos.ServiceProdutos.DadosUsuarioResponse> DadosUsuarioAsync(string login, string senha, string erro) {
            ConsultaAlteraProdutos.ServiceProdutos.DadosUsuarioRequest inValue = new ConsultaAlteraProdutos.ServiceProdutos.DadosUsuarioRequest();
            inValue.Body = new ConsultaAlteraProdutos.ServiceProdutos.DadosUsuarioRequestBody();
            inValue.Body.login = login;
            inValue.Body.senha = senha;
            inValue.Body.erro = erro;
            return ((ConsultaAlteraProdutos.ServiceProdutos.ServiceProdutosSoap)(this)).DadosUsuarioAsync(inValue);
        }
    }
}
