USE PEDIDOS

DROP TABLE CATEGORIAS

CREATE TABLE CATEGORIAS
( COD_CAT		INT		IDENTITY	PRIMARY KEY,
  CATEGORIA		VARCHAR(30),
  COD_CAT_PAI	INT )
 

  
INSERT INTO CATEGORIAS ( CATEGORIA,COD_CAT_PAI)
VALUES ('PRODUTO ACABADO',0)
--
INSERT INTO CATEGORIAS ( CATEGORIA,COD_CAT_PAI)
VALUES ('MATERIA PRIMA',0)
--
INSERT INTO CATEGORIAS ( CATEGORIA,COD_CAT_PAI)
VALUES ('INSUMOS',0)
--
INSERT INTO CATEGORIAS ( CATEGORIA,COD_CAT_PAI)
VALUES ('MÁQUINAS/EQUIPAMENTOS',0)
--
INSERT INTO CATEGORIAS ( CATEGORIA,COD_CAT_PAI)
VALUES ('MATERIAL ESCRITÓRIO',0)
--
INSERT INTO CATEGORIAS ( CATEGORIA,COD_CAT_PAI)
VALUES ('VEÍCULOS',0)
--
INSERT INTO CATEGORIAS ( CATEGORIA,COD_CAT_PAI)
VALUES ('ABRIDOR',1)
--
INSERT INTO CATEGORIAS ( CATEGORIA,COD_CAT_PAI)
VALUES ('ABRIDOR DE LATAS',7)
--
INSERT INTO CATEGORIAS ( CATEGORIA,COD_CAT_PAI)
VALUES ('ABRIDOR DE GARRAFAS',7)
--
INSERT INTO CATEGORIAS ( CATEGORIA,COD_CAT_PAI)
VALUES ('PORTA LÁPIS',1)
--
INSERT INTO CATEGORIAS ( CATEGORIA,COD_CAT_PAI)
VALUES ('MODELO A',10)
--
INSERT INTO CATEGORIAS ( CATEGORIA,COD_CAT_PAI)
VALUES ('MODELO B',10)
--
INSERT INTO CATEGORIAS ( CATEGORIA,COD_CAT_PAI)
VALUES ('MODELO C',10)
--
INSERT INTO CATEGORIAS ( CATEGORIA,COD_CAT_PAI)
VALUES ('CANETA',1)
--
INSERT INTO CATEGORIAS ( CATEGORIA,COD_CAT_PAI)
VALUES ('TINTEIRO',14)
--
INSERT INTO CATEGORIAS ( CATEGORIA,COD_CAT_PAI)
VALUES ('ESFEROGRÁFICA',14)
--
INSERT INTO CATEGORIAS ( CATEGORIA,COD_CAT_PAI)
VALUES ('PONTA POROSA',14)
--
INSERT INTO CATEGORIAS ( CATEGORIA,COD_CAT_PAI)
VALUES ('EXECUTIVO',15)
--
INSERT INTO CATEGORIAS ( CATEGORIA,COD_CAT_PAI)
VALUES ('STANDARD',15)
--
INSERT INTO CATEGORIAS ( CATEGORIA,COD_CAT_PAI)
VALUES ('PARA QUADRO BRANCO ',17)
--
INSERT INTO CATEGORIAS ( CATEGORIA,COD_CAT_PAI)
VALUES ('PARA PAPEL',17)
--
INSERT INTO CATEGORIAS ( CATEGORIA,COD_CAT_PAI)
VALUES ('RESINA PLÁSTICA',2)
--

SELECT * from CATEGORIAS
