//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultaAlteraProdutos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUTOS
    {
        public int ID_PRODUTO { get; set; }
        public string COD_PRODUTO { get; set; }
        public string DESCRICAO { get; set; }
        public Nullable<short> COD_UNIDADE { get; set; }
        public Nullable<short> COD_TIPO { get; set; }
        public Nullable<decimal> PRECO_CUSTO { get; set; }
        public Nullable<decimal> PRECO_VENDA { get; set; }
        public Nullable<int> QTD_ESTIMADA { get; set; }
        public Nullable<int> QTD_REAL { get; set; }
        public Nullable<int> QTD_MINIMA { get; set; }
        public string CLAS_FISC { get; set; }
        public Nullable<int> IPI { get; set; }
        public Nullable<decimal> PESO_LIQ { get; set; }
    
        public virtual TIPOPRODUTO TIPOPRODUTO { get; set; }
        public virtual UNIDADES UNIDADES { get; set; }
    }
}
