//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultaAlteraProdutos
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public int ID_USER { get; set; }
        public string NOME { get; set; }
        public string USER_LOGIN { get; set; }
        public string USER_PWS { get; set; }
        public Nullable<short> NIVEL { get; set; }
    }
}
