//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientWebApp.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name texto from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TiraAcento", ReplyAction="*")]
        ClientWebApp.ServiceReference1.TiraAcentoResponse TiraAcento(ClientWebApp.ServiceReference1.TiraAcentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TiraAcento", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientWebApp.ServiceReference1.TiraAcentoResponse> TiraAcentoAsync(ClientWebApp.ServiceReference1.TiraAcentoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TiraAcentoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TiraAcento", Namespace="http://tempuri.org/", Order=0)]
        public ClientWebApp.ServiceReference1.TiraAcentoRequestBody Body;
        
        public TiraAcentoRequest() {
        }
        
        public TiraAcentoRequest(ClientWebApp.ServiceReference1.TiraAcentoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TiraAcentoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string texto;
        
        public TiraAcentoRequestBody() {
        }
        
        public TiraAcentoRequestBody(string texto) {
            this.texto = texto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TiraAcentoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TiraAcentoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientWebApp.ServiceReference1.TiraAcentoResponseBody Body;
        
        public TiraAcentoResponse() {
        }
        
        public TiraAcentoResponse(ClientWebApp.ServiceReference1.TiraAcentoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TiraAcentoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TiraAcentoResult;
        
        public TiraAcentoResponseBody() {
        }
        
        public TiraAcentoResponseBody(string TiraAcentoResult) {
            this.TiraAcentoResult = TiraAcentoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : ClientWebApp.ServiceReference1.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<ClientWebApp.ServiceReference1.Service1Soap>, ClientWebApp.ServiceReference1.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientWebApp.ServiceReference1.TiraAcentoResponse ClientWebApp.ServiceReference1.Service1Soap.TiraAcento(ClientWebApp.ServiceReference1.TiraAcentoRequest request) {
            return base.Channel.TiraAcento(request);
        }
        
        public string TiraAcento(string texto) {
            ClientWebApp.ServiceReference1.TiraAcentoRequest inValue = new ClientWebApp.ServiceReference1.TiraAcentoRequest();
            inValue.Body = new ClientWebApp.ServiceReference1.TiraAcentoRequestBody();
            inValue.Body.texto = texto;
            ClientWebApp.ServiceReference1.TiraAcentoResponse retVal = ((ClientWebApp.ServiceReference1.Service1Soap)(this)).TiraAcento(inValue);
            return retVal.Body.TiraAcentoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientWebApp.ServiceReference1.TiraAcentoResponse> ClientWebApp.ServiceReference1.Service1Soap.TiraAcentoAsync(ClientWebApp.ServiceReference1.TiraAcentoRequest request) {
            return base.Channel.TiraAcentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientWebApp.ServiceReference1.TiraAcentoResponse> TiraAcentoAsync(string texto) {
            ClientWebApp.ServiceReference1.TiraAcentoRequest inValue = new ClientWebApp.ServiceReference1.TiraAcentoRequest();
            inValue.Body = new ClientWebApp.ServiceReference1.TiraAcentoRequestBody();
            inValue.Body.texto = texto;
            return ((ClientWebApp.ServiceReference1.Service1Soap)(this)).TiraAcentoAsync(inValue);
        }
    }
}
