USE PEDIDOS

CREATE TABLE USUARIOS
(
	ID_USER			INT		IDENTITY,
	NOME			VARCHAR(30),
	USER_LOGIN		VARCHAR(10),
	USER_PWS		VARCHAR(10),
	NIVEL			SMALLINT,
	CONSTRAINT PK_USUARIOS PRIMARY KEY (ID_USER)
)

ALTER TABLE USUARIOS ADD 
CONSTRAINT UQ_USUARIOS_USER_LOGIN UNIQUE(USER_LOGIN)

INSERT INTO USUARIOS
VALUES ('CARLOS MAGNO', 'magno', 'magno', 100),
       ('zé mane', 'ze', 'ze', 10)

SELECT * FROM USUARIOS