//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExEDM_Pedidos.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=NOTEDELL\\SQLEXPRESS;Initial Catalog=PEDIDOS;Integrated Security=True")]
        public string PEDIDOSConnectionString {
            get {
                return ((string)(this["PEDIDOSConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=2P35_INSTRUTOR\\SQLEXPRESS;Initial Catalog=PEDIDOS;Integrated Security" +
            "=True")]
        public string PEDIDOSConnectionString1 {
            get {
                return ((string)(this["PEDIDOSConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=321P9_INSTRUTOR\\SQLEXPRESS;Initial Catalog=PEDIDOS;Integrated Securit" +
            "y=True")]
        public string PEDIDOSConnectionString2 {
            get {
                return ((string)(this["PEDIDOSConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=221P9_INSTRUTOR\\SQLEXPRESS;Initial Catalog=PEDIDOS;Integrated Securit" +
            "y=True")]
        public string PEDIDOSConnectionString3 {
            get {
                return ((string)(this["PEDIDOSConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=3P25_INSTRUTOR\\SQLEXPRESS;Initial Catalog=PEDIDOS;Integrated Security" +
            "=True")]
        public string PEDIDOSConnectionString4 {
            get {
                return ((string)(this["PEDIDOSConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=321P7_INSTRUTOR\\SQLEXPRESS;Initial Catalog=PEDIDOS;Integrated Securit" +
            "y=True")]
        public string PEDIDOSConnectionString5 {
            get {
                return ((string)(this["PEDIDOSConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=2P40_INSTRUTOR\\SQLEXPRESS;Initial Catalog=PEDIDOS;Integrated Security" +
            "=True")]
        public string PEDIDOSConnectionString6 {
            get {
                return ((string)(this["PEDIDOSConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=3P14_INSTRUTOR\\SQLEXPRESS;Initial Catalog=PEDIDOS;Integrated Security" +
            "=True")]
        public string PEDIDOSConnectionString7 {
            get {
                return ((string)(this["PEDIDOSConnectionString7"]));
            }
        }
    }
}
