//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExEDM_Pedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDOS
    {
        public int NUM_PEDIDO { get; set; }
        public Nullable<int> CODCLI { get; set; }
        public Nullable<short> CODVEN { get; set; }
        public Nullable<System.DateTime> DATA_EMISSAO { get; set; }
        public Nullable<decimal> VLR_TOTAL { get; set; }
        public string SITUACAO { get; set; }
        public string OBSERVACOES { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
        public virtual VENDEDORES VENDEDORES { get; set; }
    }
}
