//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExEDM_Pedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENDEDORES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VENDEDORES()
        {
            this.PEDIDOS = new HashSet<PEDIDOS>();
        }
    
        public short CODVEN { get; set; }
        public string NOME { get; set; }
        public string FANTASIA { get; set; }
        public string ENDERECO { get; set; }
        public string BAIRRO { get; set; }
        public string CIDADE { get; set; }
        public string ESTADO { get; set; }
        public string CEP { get; set; }
        public string CPF { get; set; }
        public string RG { get; set; }
        public string FONE { get; set; }
        public string FAX { get; set; }
        public string E_MAIL { get; set; }
        public Nullable<System.DateTime> DATA_CAD { get; set; }
        public Nullable<System.DateTime> DATA_NASC { get; set; }
        public Nullable<decimal> PORC_COMISSAO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEDIDOS> PEDIDOS { get; set; }
    }
}
