USE PEDIDOS

CREATE TABLE TABELACOMDOCSFORA
( ID	INT	IDENTITY	PRIMARY KEY,
  DESCRICAO	VARCHAR(40),
  PATH_DOCTO		VARCHAR(1000)
  )
  
  
CREATE TABLE TABELACOMDOCSDENTRO
( ID	INT	IDENTITY	PRIMARY KEY,
  DESCRICAO	VARCHAR(40),
  TIPO VARCHAR(5),
  DOCTO VARBINARY(MAX)
  )  