USE PEDIDOS
GO
-- TABELAS DO BANCO DE DADOS
SELECT *  FROM SYSOBJECTS
--
SELECT NAME, ID, XTYPE  FROM SYSOBJECTS
--
SELECT NAME  FROM SYSOBJECTS 
WHERE XTYPE = 'U' AND name NOT LIKE 'SYS%'
ORDER BY NAME

select * from syscolumns

-- ESTRUTURA DA TABELA --------------------------------------
SELECT C.COLID, C.NAME AS COLUNAS, 
       DT.NAME AS TIPO, C.length AS BYTES, C.xprec AS PRECISAO, 
       C.xscale AS DECIMAIS 
FROM SYSOBJECTS T JOIN SYSCOLUMNS C ON T.id = C.id 
     JOIN SYSTYPES DT ON C.xtype = DT.xtype
WHERE T.XTYPE = 'U' AND T.name = 'PEDIDOS' 
ORDER BY C.COLID;

-- ÍNDICES DA TABELA ----------------------------------------
SELECT IX.NAME AS NOME_INDICE, C.name AS CAMPO, IX.type_desc
FROM SYS.INDEXES IX
	 JOIN SYSOBJECTS TABELA ON IX.OBJECT_ID = TABELA.ID 
	 JOIN sys.index_columns IC ON IC.object_id = IX.object_id AND IC.index_id = IX.index_id
	 JOIN SYSCOLUMNS C ON C.id = IC.object_id AND IC.column_id = C.colid
WHERE TABELA.name = 'CLIENTES'

-- DADOS DA TABELA ----------------------------------------
SELECT * FROM tabela


--==========================================
DECLARE @NOME VARCHAR(30) = '%JOSE%'
SELECT * FROM EMPREGADOS 
WHERE NOME LIKE @NOME
---

DECLARE @SALARIO FLOAT = 5000
SELECT * FROM EMPREGADOS
WHERE SALARIO > @SALARIO
---

DECLARE @ORDEM VARCHAR(10) = 'NOME'
SELECT * FROM EMPREGADOS
ORDER BY @ORDEM
---

DECLARE @TABELA VARCHAR(20) = 'EMPREGADOS'
SELECT * FROM @TABELA

SELECT * FROM EMPREGADOS