USE PEDIDOS
-- Totalizar as vendas do vendedor por mês
-- forma tradicional
SELECT CODVEN, MONTH(DATA_EMISSAO) AS MES, SUM(VLR_TOTAL) AS TOT_VENDIDO
FROM PEDIDOS
WHERE YEAR(DATA_EMISSAO) = 2006
GROUP BY CODVEN, MONTH(DATA_EMISSAO)
ORDER BY CODVEN, MES

-- "PIVOTANDO"
-- Ex. 1a:
SELECT CODVEN, [1] AS MES1, [2] AS MES2, [3] AS MES3, [4] AS MES4, [5] AS MES5, 
               [6] AS MES6, [7] AS MES7, [8] AS MES8, [9] AS MES9, [10] AS MES10,
               [11] AS MES11, [12] AS MES12
FROM (SELECT CODVEN, VLR_TOTAL, MONTH(DATA_EMISSAO) AS MES
      FROM PEDIDOS
      WHERE YEAR(DATA_EMISSAO) = 2006) P
      PIVOT( SUM(VLR_TOTAL) FOR MES IN ([1],[2],[3],[4],[5],[6],[7],[8],[9],[10],[11],[12])) AS PVT
ORDER BY 1 

-- Ex. 1b:
SELECT PVT.CODVEN, V.NOME, [1] AS Jan, [2] AS Fev, [3] AS Mar, [4] AS Abr, [5] AS Mai, 
               [6] AS Jun, [7] AS Jul, [8] AS Ago, [9] AS [Set], [10] AS [Out],
               [11] AS Nov, [12] AS Dez
FROM (SELECT CODVEN, VLR_TOTAL, MONTH(DATA_EMISSAO) AS MES
      FROM PEDIDOS
      WHERE YEAR(DATA_EMISSAO) = 2006) AS P
      PIVOT( SUM(VLR_TOTAL) FOR MES IN ([1],[2],[3],[4],[5],[6],[7],[8],[9],[10],[11],[12])) AS PVT
JOIN VENDEDORES V ON PVT.CODVEN = V.CODVEN   
ORDER BY 1        

-- Ex. 2:
SELECT CODCLI, [1] AS MES1, [2] AS MES2, [3] AS MES3, [4] AS MES4, [5] AS MES5, 
               [6] AS MES6, [7] AS MES7, [8] AS MES8, [9] AS MES9, [10] AS MES10,
               [11] AS MES11, [12] AS MES12
FROM (SELECT CODCLI, VLR_TOTAL, MONTH(DATA_EMISSAO) AS MES
      FROM PEDIDOS
      WHERE YEAR(DATA_EMISSAO) = 2006) P
   PIVOT( SUM(VLR_TOTAL) FOR MES IN ([1],[2],[3],[4],[5],[6],[7],[8],[9],[10],[11],[12])) AS PVT
ORDER BY 1        
-- Ex. 2b: Mostrar o nome do cliente






-- Ex. 3a
SELECT ID_PRODUTO, [1] AS MES1, [2] AS MES2, [3] AS MES3, [4] AS MES4, [5] AS MES5, 
               [6] AS MES6, [7] AS MES7, [8] AS MES8, [9] AS MES9, [10] AS MES10,
               [11] AS MES11, [12] AS MES12
FROM (SELECT I.ID_PRODUTO, I.QUANTIDADE*I.PR_UNITARIO AS VALOR, MONTH(P.DATA_EMISSAO) AS MES
      FROM PEDIDOS P JOIN ITENSPEDIDO I ON P.NUM_PEDIDO = I.NUM_PEDIDO
      WHERE YEAR(P.DATA_EMISSAO) = 2006) I
   PIVOT( SUM(VALOR) FOR MES IN ([1],[2],[3],[4],[5],[6],[7],[8],[9],[10],[11],[12])) AS PVT
ORDER BY 1     

-- Ex. 3b: Mostrar o nome do produto







-- Ex. 4:
SELECT ANO, [1] AS MES1, [2] AS MES2, [3] AS MES3, [4] AS MES4, [5] AS MES5, 
               [6] AS MES6, [7] AS MES7, [8] AS MES8, [9] AS MES9, [10] AS MES10,
               [11] AS MES11, [12] AS MES12
FROM (SELECT YEAR(DATA_EMISSAO) AS ANO, VLR_TOTAL, MONTH(DATA_EMISSAO) AS MES
      FROM PEDIDOS) P
   PIVOT( SUM(VLR_TOTAL) FOR MES IN ([1],[2],[3],[4],[5],[6],[7],[8],[9],[10],[11],[12])) AS PVT
ORDER BY 1 

-- Ex. 5:
SELECT MES, [2005] AS ANO_2005, [2006] AS ANO_2006, [2007] AS ANO_2007, [2008] AS ANO_2008
FROM ( SELECT MONTH(DATA_EMISSAO) AS MES,  VLR_TOTAL, YEAR(DATA_EMISSAO) AS ANO FROM PEDIDOS ) P
PIVOT( SUM(VLR_TOTAL) FOR ANO IN ([2005],[2006],[2007],[2008]) )     AS PVT
ORDER BY 1

